version: '3.8'

services:
  # Nama layanan aplikasi kamu
  inspira-app:
    build: .
    container_name: inspira_container
    # Menghubungkan port 8080 di STB ke port 80 di dalam Docker
    ports:
      - "8081:80"
    # Menghubungkan folder di STB dengan folder di dalam Docker (agar file sinkron)
    volumes:
      - .:/var/www/html
    # Memberi tahu CodeIgniter bahwa kita dalam mode pengembangan
    environment:
      - CI_ENVIRONMENT=development